### ISSUE TITLE
Arbitrary samba configuration options

### ISSUE THREAD

**Issue by goetzk** [bertvv/ansible-role-samba#32]
Hi,
It would be good to see support for arbitrary configuration options added, OR, the ability to include other files.

As it stands there are lots of samba configuration options which might need a tweak which can't be used because the template overwrites them on every ansible run.

**Comment by goetzk** [comment]
As a suggestion (which seems like it might be a better way to go? I thought about using samba's include functionality instead (ignore the fruit options, they're something else I'm playing with)

```
Karls-MacBook-Air:bertvv.samba kgoetz$ git diff
diff --git a/templates/smb.conf.j2 b/templates/smb.conf.j2
index 27e8fa5..6634016 100755
--- a/templates/smb.conf.j2
+++ b/templates/smb.conf.j2
@@ -67,6 +67,10 @@
   nt pipe support = no
 {% endif %}
 
+{% if samba_global_include is defined %}
+  include = {{ samba_global_include }}
+{% endif %}
+
 {% if samba_load_homes %}
 ## Make home directories accessible
 [homes]
@@ -75,6 +79,10 @@
   writable = yes
 {% endif %}
 
+{% if samba_home_include is defined %}
+  include = {{ samba_home_include }}
+{% endif %}
+
 {% if samba_shares|length > 0 %}
 ## Shared directories
 {% for share in samba_shares %}
@@ -110,11 +118,18 @@
 {% endif %}
 {% if share.writable is defined %}
   writable = {{ share.writable }}
+{% endif %}
+{% if share.timemachine is defined %}
+  fruit:time machine = {{ share.timemachine }}
 {% endif %}
   create mode = {{ share.create_mode|default('0664') }}
   force create mode = {{ share.force_create_mode|default('0664') }}
   directory mode = {{ share.directory_mode|default('0775') }}
   force directory mode = {{ share.force_directory_mode|default('0775') }}
+{% if share.file_include is defined %}
+  include = {{ share.file_include }}
+{% endif %}
 
 {% endfor %}
 {% endif%}
+
```

Would you like me to do this up as a PR? It would need updated documentation but the conditionals are working already.

**Comment by bertvv** [comment]
I would love this as a PR! Thank you so much for taking the time to look into this!

**Comment by goetzk** [comment]
Quickly checking in to say I haven't forgotten this, I just haven't had time to complete the work yet!

**Comment by goetzk** [comment]
This should be closed when #35 is merged.

**Comment by goetzk** [comment]
hi @bertvv,

Have you had a chance to look at the open PRs? Anything else you'd like changed or reviewed in them?

**Comment by bertvv** [comment]
Sorry for the delay, @goetzk ! Working on it right now.

You may have seen the failing checks on all PRs. The cause was that my test environment was broken, at least for testing on Ubuntu 18.04. I needed some time to get that fixed first.
I'm adding your features in the [test playbook](https://github.com/bertvv/ansible-role-samba/blob/docker-tests/test.yml) and will release a new version as soon as that's done and all checks pass! One thing that my test environment cannot check is whether the TimeMachine share can actually be used as a backup target. I'm sure you'll let me know if it doesn't work, right? ;-)
Thank you so much for your great contributions!

**Comment by goetzk** [comment]
I'm currently backing up to it :) Its configured with the following section
```
  samba_shares:
      - name: TimeMachine
        comment: Backup target for Time Machines
        vfs_objects:
          # If missing these you'll see "The selected network backup disk does not support the required capabilities."
          - name: fruit
            options:
            - name: time machine
              value: 'yes'
            # - name: time machine max size
            #   value: 1T
          - name: streams_xattr
        path: /srv/timemachine
        write_list: timemachine
        owner: timemachine
        group: timemachine
        public: 'no'
        guest_ok: 'no'
        browseable: 'no'
```

I'm happy to post up my backup host playbook if it helps.
