### ISSUE TITLE
Fout in ansible documentatie: samba_home(s)_include

### ISSUE THREAD

**Issue by KeanuNys** [bertvv/ansible-role-samba#37]
## Expected Behavior
`templates/home-include.conf` wordt gekopieerd naar `/etc/samba/` door gebruik van de volgende variable: `samba_home_include: home-include.conf` 

## Current Behavior
De config file wordt niet gekopieerd van de host naar de virtual machine.

## Possible Solution
- Gebruik de variable `samba_homes_include` en verander de documentatie zodat die overeenkomt met de definitie in tasks/main.yml
- Of verander de definitie van de module op lijn 100 in tasks/main.yml naar `src: "{{ samba_homes_include }}"` zodat dit overeenkomt met de documentatie

**Comment by KeanuNys** [comment]
Momenteel staat in `mail.yml` `samba_homes_include` met een s, maar in smb.conf.j2 staat `samba_home_include` zonder s zoals in de documentatie.
mail.yml:
```
- name: Install homes include file
  template:
    src: "{{ samba_homes_include }}"
    dest: "{{ samba_configuration_dir }}"
    validate: 'testparm -s %s'
  when: samba_homes_include is defined
  notify:
    - Restart Samba services
````
smb.conf.j2:
```
{% if samba_home_include is defined %}
  include = {{ samba_home_include }}
{% endif %}
```
