### ISSUE TITLE
Fails if filesystem is EXFAT

### ISSUE THREAD

**Issue by achembarpu** [bertvv/ansible-role-samba#56]
Hey, thanks so much for this ansible role!

I am trying to get this up and running, to share data from an EXFAT drive. However, it fails at `TASK [bertvv.samba : Create share directories]`. This because the EXFAT filesystem does not support chown/etc, and so chrgrp is failing.

Example error:

```yaml
failed: [nas] (item={'name': 'documents', 'comment': 'Documents', 'guest_ok': True, 'public': True, 'writable': True, 'browsable': True, 'path': '/server/documents'}) => changed=false
  ansible_loop_var: item
  gid: 0
  group: root
  item:
    browsable: true
    comment: Documents
    guest_ok: true
    name: documents
    path: /server/documents
    public: true
    writable: true
  mode: '0777'
  msg: chgrp failed
  owner: root
  path: /server/documents
  size: 262144
  state: directory
  uid: 0
```

is it possible to skip/handle this task differently based on the filesystem?

Thanks!
