### ISSUE TITLE
No support for "allow hosts"

### ISSUE THREAD

**Issue by breakid** [bertvv/ansible-role-samba#70]
There is currently no way to restrict shares by host / subnet. 

Basic functionality can be accomplished by adding the following to templates/smb.conf.j2. I recommend including it after "force directory mode = {{ share.force_directory_mode|default('0775') }}".

```jinja
{% if share.allow_hosts is defined %}
  allow hosts = {% for entry in share.allow_hosts %}{{ entry }}{% if not loop.last %}, {% endif %}{% endfor %}
{% endif %}
```

Example Configuration:
```yaml
samba_shares:
  - name: /srv/shares/test
    write_list: +users
    setype: public_content_rw_t
    allow_hosts:
      - 192.168.1.0/24
      - 172.16.10.0/255.255.255.0
```
